version: '3'
services:
  web:
    build: .
    ports:
      - "8081:80"
    volumes:
      - ./index.php:/var/www/html/index.php
      - ./handle-form.php:/var/www/html/handle-form.php
      - ./success-page.php:/var/www/html/success-page.php
      - ./functions.php:/var/www/html/functions.php
      - ./style.css:/var/www/html/style.css
      - ./form_data.csv:/var/www/html/form_data.csv
      - ./Connection.class.php:/var/www/html/Connection.class.php
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:
